
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-frontiers-s26-11
owner: ucsb-cs156-s26
repo_name: proj-frontiers-s26-11
pull_requests: [{"author":{"id":"U_kgDOBYEbCw","is_bot":false,"login":"yensydney","name":"Nini Yen"},"headRefName":"ny-add-post-endpoint","number":32,"title":"Add endpoint to hide base permission warning","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-11/pull/32"},{"author":{"id":"U_kgDOCuiqvg","is_bot":false,"login":"RushabhTaneja","name":"Rushabh"},"headRefName":"rt-logOutput","number":27,"title":"Changed log messages","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-11/pull/27"},{"author":{"id":"U_kgDOCwAENg","is_bot":false,"login":"anishjai56","name":"Anish Jaiswal"},"headRefName":"student_course_show_page","number":26,"title":"placeholder for studentcourse show page","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-11/pull/26"},{"author":{"id":"MDQ6VXNlcjgyNzg0NzI0","is_bot":false,"login":"itbolt","name":""},"headRefName":"tn-default-base-permission","number":25,"title":"Add default base permission GitHub GraphQL endpoint","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-11/pull/25"},{"author":{"id":"MDQ6VXNlcjY5MzYxMDgy","is_bot":false,"login":"Hudinid","name":"Brian Hu"},"headRefName":"bh-deleterepos","number":24,"title":"bh - Adding Repo Delete Draft","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-11/pull/24"}]
